# name: SonarQube Scan

# on:
#   push:
#     branches:
#       - main

# jobs:
#   sonar:
#     name: SonarQube Scan
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: '11'

#       - name: Build with Maven
#         run: mvn clean install

#       - name: Run SonarQube Scanner
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         run: |
#           mvn sonar:sonar \
#             -Dsonar.projectKey=sqp_a959425c1c6d5aecc48fa8a1b6a3e284c5b11c7b \ 
#             -Dsonar.host.url=https://sonarqube.labs.unimar.br/ 
#             -Dsonar.login=$TOKEN_SONARQUBE